# this build instruction is used in container
golang:build:
- name: editorconfig-checker
  env: &env
  - APP=editorconfig-checker
  # source: https://github.com/editorconfig-checker/editorconfig-checker.git
  - VERSION=2.3.5
  matrix@file: &matrix .dukkha/specs/app-matrix-all.yml
  chdir@env: /app/build/${APP}
  path: ./cmd/editorconfig-checker/
  outputs@env:
  - /app/build/${APP}.${MATRIX_KERNEL}.${MATRIX_ARCH}
  cgo:
    enabled: false
  ldflags@env:
  - -X "main.version=${VERSION}"
  tags:
  - netgo
  extra_args:
  - -trimpath
  - -mod=readonly

buildah:bud:
- name: editorconfig-checker
  env: *env
  matrix@file: *matrix
  hooks:
    before:
    - shell@env: |-
        [ -d build/${APP} ] && exit 0

        git clone --branch ${VERSION} \
          https://github.com/editorconfig-checker/editorconfig-checker.git \
          build/${APP}

  dockerfile: app/golang-nocgo.dockerfile
  image_names@file|env: &image_names |-
    templates/image-names/no-rootfs-info/env[APP:VERSION].yml
  extra_args@file|env|template: templates/image-extra-args/env[APP].yml

buildah:push:
- name: editorconfig-checker
  env: *env
  hooks:
    before:
    - task: buildah:login(ghcr)
  matrix@file: *matrix
  image_names@file|env: *image_names
