# this build instruction is used in container
golang:build:
- name: editorconfig-checker
  matrix@file: &matrix .dukkha/specs/app-matrix-all.yml
  chdir: /app/build/editorconfig-checker
  path: ./cmd/editorconfig-checker/
  outputs:
  - /app/build/editorconfig-checker.${MATRIX_KERNEL}.${MATRIX_ARCH}
  cgo:
    enabled: false
  ldflags@env:
  - -X main.version="$(git -C /app/build/editorconfig-checker describe --tags)"
  tags:
  - netgo
  extra_args:
  - -trimpath
  - -mod=readonly

buildah:bud:
- name: editorconfig-checker
  matrix@file: *matrix
  hooks:
    before:
    - shell: |-
        [ -d build/editorconfig-checker ] && exit 0

        git clone --branch 2.3.5 \
          https://github.com/editorconfig-checker/editorconfig-checker.git \
          build/editorconfig-checker

  dockerfile: app/golang-nocgo.dockerfile
  image_names@env: &image_names
  - image: ghcr.io/arhat-dev/editorconfig-checker:latest-${MATRIX_ARCH}
    manifest: ghcr.io/arhat-dev/editorconfig-checker:latest
  - image: ghcr.io/arhat-dev/editorconfig-checker:$(git -C build/editorconfig-checker describe --tags )-${MATRIX_ARCH}
    manifest: ghcr.io/arhat-dev/editorconfig-checker:$(git -C build/editorconfig-checker describe --tags )
  extra_args@env:
  - --pull-always
  - --build-arg
  - APP=editorconfig-checker
  - --build-arg
  - MATRIX_ROOTFS=${MATRIX_ROOTFS}
  - --build-arg
  - MATRIX_ARCH=${MATRIX_ARCH}

buildah:push:
- name: editorconfig-checker
  hooks:
    before:
    - task: buildah:login(ghcr)
  matrix@file: *matrix
  image_names@env: *image_names
