bootstrap:
  env:
  - DEBIAN_VERSION=buster
  - ALPINE_VERSION=3.13
  # source: https://github.com/golang/go
  - GO_VERSION=1.16
  # source: https://github.com/rust-lang/rust
  - RUST_VERSION=1.53
  # source: https://github.com/multiarch/qemu-user-static
  - QEMU_VERSION=5.2.0-2

tools:
  buildah:
  - name: local
    cmd: [buildah]
  - name: in-docker
    # create a docker volume for buildah
    #
    # $ docker volume create buildah-dockerfile
    cmd:
    - |-
      docker run -it --rm \
        --workdir $(pwd) \
        -v $(pwd):$(pwd) \
        --security-opt label=disable \
        --security-opt seccomp=unconfined \
        -v buildah-dockerfile:/var/lib/containers \
        --device /dev/fuse:rw \
        quay.io/buildah/stable \
        buildah

  golang:
  - name: local

shells:
- name: sh
  cmd: [sh]

buildah:login:
- name: ghcr
  registry: ghcr.io
  username: ${GHCR_USER}
  password@env: ${GHCR_PASS}
