include:
- common/dukkha.yaml
- app/*/dukkha.yaml
- nix/dukkha.yaml
- java/*/dukkha.yaml
- golang/*/dukkha.yaml
- python/*/dukkha.yaml
- ruby/*/dukkha.yaml
- kind/dukkha.yaml

bootstrap:
  env:
  - IMAGE_REPO=ghcr.io/arhat-dev
  # source(docker): docker.io/library/debian
  - DEBIAN_VERSION=buster
  # source(docker): docker.io/library/alpine
  - ALPINE_VERSION=3.13
  # source(docker): docker.io/library/golang
  - GO_VERSION=1.16
  # source(docker): docker.io/library/rust
  - RUST_VERSION=1.53
  # source(git-tags): https://github.com/multiarch/qemu-user-static
  - QEMU_VERSION=5.2.0-2
  # source(docker): docker.io/library/ruby
  - RUBY_VERSION=2.7
  # source(git-tags): https://github.com/krallin/tini
  - TINI_VERSION=v0.19.0
  # source(git-tags): https://github.com/NixOS/nix
  - NIX_VERSION=2.3.14
  # source(git-tags): https://github.com/elastic/elasticsearch
  - ES7_VERSION=v7.13.3
  # source(git-tags): https://github.com/protocolbuffers/protobuf
  - PROTOC_VERSION=v3.17.3
  # source(git-tags): https://github.com/apache/maven
  - MAVEN3_VERSION=3.8.1

tools:
  buildah:
  - name: local
    cmd: [buildah]
  - name: in-docker
    # create a docker volume for buildah
    #
    # $ docker volume create buildah-dockerfile
    cmd@env:
    - docker
    - run
    - -it
    - --rm
    - --workdir
    - ${DUKKHA_WORKING_DIR}
    - -v
    - ${DUKKHA_WORKING_DIR}:${DUKKHA_WORKING_DIR}
    - --privileged
    # - --security-opt
    # - label=disable
    # - --security-opt
    # - seccomp=unconfined
    - -v
    - buildah-dockerfile:/var/lib/containers
    - --device
    - /dev/fuse:rw
    - quay.io/buildah/stable
    - buildah

  golang:
  - name: local
    env:
    - GOPROXY=direct
    - GOSUMDB=off
  workflow:
  - name: local
  - name: in-docker
  docker:
  - name: local

shells:
- name: sh
  cmd: [sh]

buildah:login:
- &ghcr_login
  name: ghcr
  registry: ghcr.io
  username: ${GHCR_USER}
  password@env: ${GHCR_PASS}

docker:login:
- *ghcr_login

workflow:run:
- name: build-common-images
  matrix: &kind_matrix
    kernel:
    - linux
    target:
    - base
    - builder
    - container
    language:
    - go
    - python3.6
    - python3.7
    - python3.8
    - python3.9
    - rust
  hooks:
    after:
    - shell: buildah images
  jobs:
  - task@env: |-
      buildah:build(
        ${MATRIX_KERNEL}/${MATRIX_TARGET},
        { language: [${MATRIX_LANGUAGE}] }
      )
  - task@env: |-
      buildah:push(
        ${MATRIX_KERNEL}/${MATRIX_TARGET},
        { language: [${MATRIX_LANGUAGE}] }
      )
