bootstrap: {}

tools:
  docker:
  - name: buildkit
    env:
    - DOCKER_BUILDKIT=1
    cmd: [docker]

  buildah:
  - name: buildah
    cmd: [buildah]

shells:
- name: sh
  env:
  - DEBIAN_VERSION=buster
  - ALPINE_VERSION=3.13
  - GO_VERSION=1.16
  # https://github.com/multiarch/qemu-user-static/releases
  - QEMU_VERSION=5.2.0-2
  cmd: [sh]
