exclude: |
  (?x)^(
    .*/patches/.*\.patch
  )$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: |-
      (?x)^(
        .*templates/.*
      )$
    args:
    - --allow-multiple-documents

- repo: local
  hooks:
  - id: update-matrix
    name: Update Common Image Build Matrix
    entry: dukkha workflow local run generate-matrix
    language: system
    pass_filenames: false
    # uncomment the following line to only run after git pull
    # stages: [post-merge]
