# glibc

[target.x86_64-unknown-linux-gnu]
linker = "gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

# musl libc

[target.x86_64-unknown-linux-musl]
linker = "gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnuabihf-gcc"
