# glibc

[target.i686-unknown-linux-gnu]
linker = "i686-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.mips-unknown-linux-gnu]
linker = "mips-linux-gnu-gcc"

[target.mipsel-unknown-linux-gnu]
linker = "mipsel-linux-gnu-gcc"

[target.mips64-unknown-linux-gnuabi64]
linker = "mips64-linux-gnu-gcc"

[target.mips64el-unknown-linux-gnuabi64]
linker = "mips64el-linux-gnu-gcc"

[target.powerpc-unknown-linux-gnu]
linker = "powerpc-linux-gnu-gcc"

[target.powerpc64-unknown-linux-gnu]
linker = "powerpc64-linux-gnu-gcc"

[target.powerpc64le-unknown-linux-gnu]
linker = "powerpc64le-linux-gnu-gcc"

[target.s390x-unknown-linux-gnu]
linker = "s390x-linux-gnu-gcc"

# musl libc

[target.i686-unknown-linux-musl]
linker = "i686-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnuabihf-gcc"

[target.mips-unknown-linux-musl]
linker = "mips-linux-gnu-gcc"

[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-gnu-gcc"
