ARG SPILO_IMAGE
FROM ${SPILO_IMAGE}

LABEL org.opencontainers.image.source https://github.com/arhat-dev/dockerfile

# TODO: install promscale extensions
ENV USE_WALG_RESTORE=true \
    USE_WALG_BACKUP=true
