name: rootfs

# # yamllint disable-line rule:truthy
# on:
#   check_run:
#     types:
#     - rerequested
#     - requested_action
#   push:
#     branches:
#     - master
#     paths:
#     - rootfs/**
#     - .github/workflows/*-rootfs.yaml
#   schedule:
#   - cron: "0 16 * * *"
#
# jobs:
