name: common

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  push:
    branches:
    - master
    paths:
    - scripts/**
    - .dukkha/**
    - .github/workflows/*-common.yaml
  schedule:
  - cron: "0 20 * * *"

jobs:
  common:
    strategy:
      matrix:
        include:
        - language:
          - go
          version:
          - "1.16"
        - language:
          - java
          version:
          - "8"
          - "11"
          - "16"
        - language:
          - python
          version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
        - language:
          - rust
          version:
          - "1.53"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dukkha
      run: |-
        mkdir -p "${HOME}/bin"
        echo "${HOME}/bin" >> $GITHUB_PATH

        docker pull ghcr.io/arhat-dev/dukkha:latest
        ctr_id=$(docker create ghcr.io/arhat-dev/dukkha:latest : 2>/dev/null)
        docker cp ${ctr_id}:/dukkha "${HOME}/bin/dukkha"

        chmod +x "${HOME}/bin/dukkha"

    - name: Build and Push Images
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        dukkha buildah local build linux/base \
          -m language=${{ matrix.language }} \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/base \
          -m language=${{ matrix.language }} \
          -m version=${{ matrix.version }}

    - name: Inspect Images
      if: always()
      run: |-
        buildah images
