# name: common
#
# # yamllint disable-line rule:truthy
# on:
#   check_run:
#     types:
#     - rerequested
#     - requested_action
#   push:
#     branches:
#     - master
#     paths:
#     - app/**
#     - scripts/**
#     - .dukkha/**
#     - .github/workflows/build.yaml
#   schedule:
#   - cron: "0 22 * * *"
#
# jobs:
#   common:
#     strategy:
#       matrix:
#         language:
#         - go
#         - python3.6
#         - python3.7
#         - python3.8
#         - python3.9
#         - rust
#       fail-fast: false
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install dukkha
#       run: |-
#         mkdir -p "${HOME}/bin"
#         echo "${HOME}/bin" >> $GITHUB_PATH
#
#         docker pull ghcr.io/arhat-dev/dukkha:latest
#         ctr_id=$(docker create ghcr.io/arhat-dev/dukkha:latest : 2>/dev/null)
#         docker cp ${ctr_id}:/dukkha "${HOME}/bin/dukkha"
#
#         chmod +x "${HOME}/bin/dukkha"
#
#     - name: Build and Push Images
#       env:
#         GHCR_USER: ${{ github.actor }}
#         GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#         sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
#         dukkha workflow local run build-common-images -m language=${{ matrix.language }}
