name: app

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 * * *"

env:
  DOCKER_BUILDKIT: "0"

jobs:
  apps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install latest docker
      run: sudo bash scripts/ci.sh install_docker
    - name: build and push app images
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        GITHUB_DOCKER_USERNAME: ${{ github.actor }}
        GITHUB_DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
        docker login ghcr.io -u="$GITHUB_DOCKER_USERNAME" -p="$GITHUB_DOCKER_PASSWORD"
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        make -j$(nproc --all) images-app
        docker images
