name: build

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  push:
    branches:
    - master
    paths:
    - app/**
    - scripts/**
    - .dukkha/**
    - .github/workflows/build.yaml
  schedule:
  - cron: "0 0 * * *"

jobs:
  common:
    strategy:
      matrix:
        language:
        # - go
        # - python3.6
        # - python3.7
        # - python3.8
        # - python3.9
        - rust
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dukkha
      run: |-
        mkdir -p "${HOME}/bin"
        echo "${HOME}/bin" >> $GITHUB_PATH

        docker pull ghcr.io/arhat-dev/dukkha:latest
        ctr_id=$(docker create ghcr.io/arhat-dev/dukkha:latest : 2>/dev/null)
        docker cp ${ctr_id}:/dukkha "${HOME}/bin/dukkha"

        chmod +x "${HOME}/bin/dukkha"

    - name: Build and Push Images
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        actions="bud push"
        targets="base builder container"
        for act in ${actions}; do
          for t in ${targets}; do
            dukkha buildah local ${act} "linux/${t}" \
              -m language=${{ matrix.language }}
          done
        done

    - name: Inspect Images
      if: always()
      run: |-
        buildah images

#   apps:
#     strategy:
#       matrix:
#         app:
#         # - proton-bridge
#         # - spilo
#         # - yamllint
#         # - kubeval
#         # - helm
#         # - conftest
#         # - editorconfig-checker
#         # - golangci-lint
#         - kine
#         - litestream
#       fail-fast: false
#     runs-on: ubuntu-20.04
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install dukkha
#       run: |-
#         mkdir -p "${HOME}/bin"
#         echo "${HOME}/bin" >> $GITHUB_PATH
#
#         docker pull ghcr.io/arhat-dev/dukkha:latest
#         ctr_id=$(docker create ghcr.io/arhat-dev/dukkha:latest : 2>/dev/null)
#         docker cp ${ctr_id}:/dukkha "${HOME}/bin/dukkha"
#
#         chmod +x "${HOME}/bin/dukkha"
#
#     - name: Build and Push ${{ matrix.app }}
#       env:
#         GHCR_USER: ${{ github.actor }}
#         GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
#       run: |-
#         sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
#
#         dukkha buildah local bud ${{ matrix.app }}
#         dukkha buildah local push ${{ matrix.app }}
#
#     - name: Inspect Images
#       if: always()
#       run: |-
#         buildah images
