name: golang

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'reason to run this workflow'
        required: false
        default: 'test'
  check_run:
    types:
    - rerequested
    - requested_action
  schedule:
  - cron: "0 12 * * FRI"

jobs:
  common:
    strategy:
      matrix:
        version:
        - "1.16.6"
        - "1.15.14"
        - "1.17rc1"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dukkha
      uses: arhat-dev/actions-setup-dukkha@master

    - name: Build and Push Images
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        dukkha buildah local build linux/base \
          -m language=golang \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/base \
          -m language=golang \
          -m version=${{ matrix.version }}

        dukkha buildah local build linux/builder \
          -m language=golang \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/builder \
          -m language=golang \
          -m version=${{ matrix.version }}

        dukkha buildah local build linux/container \
          -m language=golang \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/container \
          -m language=golang \
          -m version=${{ matrix.version }}

    - name: Inspect Images
      if: always()
      run: |-
        buildah images
