name: nix

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'reason to run this workflow'
        required: false
        default: 'test'
  check_run:
    types:
    - rerequested
    - requested_action
  schedule:
  - cron: "0 18 * * FRI"

jobs:
  build:
    strategy:
      matrix:
        rootfs:
        - alpine
        - debian
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dukkha
      uses: arhat-dev/actions-setup-dukkha@master

    - name: Enable Multiarch Support
      run: |-
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        sudo apt update
        sudo apt install -y qemu-user-static

    - name: Build and Push nix
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        dukkha buildah local build nix \
          -m rootfs=${{ matrix.rootfs }}

        dukkha buildah local push nix \
          -m rootfs=${{ matrix.rootfs }}

    - name: Inspect Images
      if: always()
      run: |-
        buildah images
