name: ruby

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  push:
    branches:
    - master
    paths:
    - common/**
    - ruby/_common/**
  schedule:
  - cron: "0 14 * * FRI"

jobs:
  common:
    strategy:
      matrix:
        version:
        - "2.7.4"
        - "3.0.2"
        - "2.6.8"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dukkha
      run: |-
        mkdir -p "${HOME}/bin"
        echo "${HOME}/bin" >> $GITHUB_PATH

        docker pull ghcr.io/arhat-dev/dukkha:latest
        ctr_id=$(docker create ghcr.io/arhat-dev/dukkha:latest : 2>/dev/null)
        docker cp ${ctr_id}:/dukkha "${HOME}/bin/dukkha"

        chmod +x "${HOME}/bin/dukkha"

    - name: Build and Push Images
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        dukkha buildah local build linux/base \
          -m language=ruby \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/base \
          -m language=ruby \
          -m version=${{ matrix.version }}

        dukkha buildah local build linux/builder \
          -m language=ruby \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/builder \
          -m language=ruby \
          -m version=${{ matrix.version }}

        dukkha buildah local build linux/container \
          -m language=ruby \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/container \
          -m language=ruby \
          -m version=${{ matrix.version }}

    - name: Inspect Images
      if: always()
      run: |-
        buildah images
