name: python

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'reason to run this workflow'
        required: false
        default: 'test'
  check_run:
    types:
    - rerequested
    - requested_action
  schedule:
  - cron: "0 16 * * FRI"

jobs:
  common:
    strategy:
      matrix:
        version:
        - "3.6.14"
        - "3.7.11"
        - "3.8.11"
        - "3.9.6"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dukkha
      run: |-
        mkdir -p "${HOME}/bin"
        echo "${HOME}/bin" >> $GITHUB_PATH

        docker pull ghcr.io/arhat-dev/dukkha:latest
        ctr_id=$(docker create ghcr.io/arhat-dev/dukkha:latest : 2>/dev/null)
        docker cp ${ctr_id}:/dukkha "${HOME}/bin/dukkha"

        chmod +x "${HOME}/bin/dukkha"

    - name: Build and Push Images
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        dukkha buildah local build linux/base \
          -m language=python \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/base \
          -m language=python \
          -m version=${{ matrix.version }}

        dukkha buildah local build linux/builder \
          -m language=python \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/builder \
          -m language=python \
          -m version=${{ matrix.version }}

        dukkha buildah local build linux/container \
          -m language=python \
          -m version=${{ matrix.version }}

        dukkha buildah local push linux/container \
          -m language=python \
          -m version=${{ matrix.version }}

    - name: Inspect Images
      if: always()
      run: |-
        buildah images
