name: go

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  push:
    branches:
    - master
    paths:
    - base/go/**
    - builder/go/**
    - container/go/**
    - scripts/go/**
    - scripts/*.mk
    - scripts/*.sh
  schedule:
  - cron: "0 0 * * *"

env:
  DOCKER_BUILDKIT: "0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Images
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        GITHUB_DOCKER_USERNAME: ${{ github.actor }}
        GITHUB_DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
        docker login ghcr.io -u="$GITHUB_DOCKER_USERNAME" -p="$GITHUB_DOCKER_PASSWORD"
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        make -j$(nproc --all) images-base-go
        make -j$(nproc --all) images-builder-go
        make -j$(nproc --all) images-container-go
        docker images
