name: kind

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  push:
    branches:
    - master
    paths:
    - .github/workflows/kind.yaml
    - scripts/*.mk
    - scripts/*.sh
  schedule:
  - cron: "0 0 * * *"

env:
  GO111MODULE: "on"
  DOCKER_BUILDKIT: "0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kube:
        - "1.14"
        - "1.15"
        - "1.16"
        - "1.17"
        - "1.18"
        - "1.19"
        - "1.20"
        - "1.21"
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Download Source of Kubernetes
      uses: actions/checkout@v2
      with:
        repository: kubernetes/kubernetes
        ref: release-${{ matrix.kube }}
        path: kube

    - name: Fetch History
      run: |
        git -C kube fetch --prune --unshallow

    - name: Install KinD
      env:
        # NOTE: once updated version of kind, need to update all e2e tests
        #       require kind with the same version
        KIND_VERSION: v0.11.1
      run: |
        mkdir -p "${HOME}/bin"
        curl -Lo "${HOME}/bin/kind" https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64
        chmod +x "${HOME}/bin/kind"
        echo "${HOME}/bin" >> $GITHUB_PATH

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build and Push Images
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
        KUBE_SRC_DIR: ${GITHUB_WORKSPACE}/kube
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        dukkha workflow local run build-kind-node-images \
          -m kube=${{ matrix.kube }}
