name: kind

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  push:
    branches:
    - master
    paths:
    - .github/workflows/kind.yaml
    - scripts/*.mk
    - scripts/*.sh
  schedule:
  - cron: "0 0 * * *"

env:
  GO111MODULE: "on"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kube:
        - "1.13"
        - "1.14"
        - "1.15"
        - "1.16"
        - "1.17"
        - "1.18"
        - "1.19"
        - "1.20"
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Download Source of Kubernetes
      uses: actions/checkout@v2
      with:
        repository: kubernetes/kubernetes
        ref: release-${{ matrix.kube }}
        path: kube

    - name: Fetch History
      run: |
        git -C kube fetch --prune --unshallow

    - name: Install KinD
      env:
        # TODO: kind v0.9.0 currently not able to handle kubernetes v1.13 node join due to kubeadm error
        #       https://github.com/kubernetes-sigs/kind/issues/1853#issuecomment-692938702
        # NOTE: once updated version of kind, need to update all e2e tests
        #       require kind with the same version
        KIND_VERSION: v0.9.0
      run: |
        if [ ${{ matrix.kube }} = '1.13' ]; then
          KIND_VERSION=v0.8.1
        fi

        mkdir -p "${HOME}/bin"
        curl -Lo "${HOME}/bin/kind" https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64
        chmod +x "${HOME}/bin/kind"
        echo "${HOME}/bin" >> $GITHUB_PATH

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build and Push Images
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        GITHUB_DOCKER_USERNAME: ${{ github.actor }}
        GITHUB_DOCKER_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: |
        docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
        docker login ghcr.io -u="$GITHUB_DOCKER_USERNAME" -p="$GITHUB_DOCKER_PASSWORD"
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        kind build node-image \
          --type docker \
          --kube-root "${GITHUB_WORKSPACE}/kube" \
          --image ghcr.io/arhat-dev/kind-node:${{ matrix.kube }}

        docker tag \
          ghcr.io/arhat-dev/kind-node:${{ matrix.kube }} \
          docker.io/arhatdev/kind-node:${{ matrix.kube }}

        docker images

        docker push ghcr.io/arhat-dev/kind-node:${{ matrix.kube }}
        docker push docker.io/arhatdev/kind-node:${{ matrix.kube }}
