name: python

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  push:
    branches:
    - master
    paths:
    - .github/workflows/python.yaml
    - base/python*/**
    - builder/python*/**
    - container/python*/**
    - scripts/python/python*.mk
    - scripts/python/*.sh
    - scripts/*.mk
    - scripts/*.sh
  schedule:
  - cron: "0 0 * * *"

env:
  DOCKER_BUILDKIT: "0"

jobs:
  build-python3-6:
    strategy:
      matrix:
        py_ver:
        - "3.6"
        - "3.7"
        - "3.8"
        - "3.9"
        # - "3.10"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Reinstall docker with platform support
      run: sudo bash scripts/ci.sh install_docker

    - name: Build and Push Images
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        GITHUB_DOCKER_USERNAME: ${{ github.actor }}
        GITHUB_DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
        docker login ghcr.io -u="$GITHUB_DOCKER_USERNAME" -p="$GITHUB_DOCKER_PASSWORD"
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        sh scripts/python/generate-base-dockerfiles.sh

        make -j$(nproc --all) images-base-python${{ matrix.py_ver }}
        make -j$(nproc --all) images-builder-python${{ matrix.py_ver }}
        make -j$(nproc --all) images-container-python${{ matrix.py_ver }}
        docker images
