name: apps-tier-1-nodejs

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'reason to run this workflow'
        required: false
        default: 'test'
  check_run:
    types:
    - rerequested
    - requested_action
  schedule:
  - cron: "0 12 * * SAT"

jobs:
  build:
    # strategy:
    #   matrix:
    #     app: []
    #   fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dukkha
      uses: arhat-dev/actions-setup-dukkha@master

    - name: Enable Multiarch Support
      run: |-
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        sudo apt update
        sudo apt install -y qemu-user-static

    # - name: Build and Push ${{ matrix.app }}
    #   env:
    #     GHCR_USER: ${{ github.actor }}
    #     GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
    #   run: |-
    #     dukkha buildah local build ${{ matrix.app }}
    #     dukkha buildah local push ${{ matrix.app }}

    - name: Inspect Images
      if: always()
      run: |-
        buildah images
